apiVersion: v1
kind: Secret
metadata:
  name: amp-publisher-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "amp-evaluation-extension.labels" . | nindent 4 }}
type: Opaque
stringData:
  client-secret: {{ .Values.ampEvaluation.publisher.clientSecret | quote }}
